artifact_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  local_data_file: news.zip
  unzip_dir: artifacts/data_ingestion


data_transformation:
  root_dir: artifacts/data_transformation
  data_path_usr: artifacts/data_ingestion/behaviors.tsv
  data_path_news: artifacts/data_ingestion/news.tsv
  col_name: ["itemId","category","subcategory","title","abstract","url","title_entities","abstract_entities"]



model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.tsv
  test_data_path: artifacts/data_transformation/valid.tsv
  news: artifacts/data_ingestion/news.tsv
  col_name: ["itemId","category","subcategory","title","abstract","url","title_entities","abstract_entities"]
  model_name: model_user.joblib
  model_content: model_content_based.joblib
  ind2user: artifacts/data_transformation/ind2user.json
  ind2item: artifacts/data_transformation/ind2uitem.json

trending_api:
  training_data: artifacts/data_transformation/train.tsv
  validation_data: artifacts/data_transformation/valid.tsv
  news_data: artifacts/data_ingestion/news.tsv
  col_name: ["itemId","category","subcategory","title","abstract","url","title_entities","abstract_entities"]
  item2ind_json: artifacts/data_transformation/item2ind.json


fullnews:
  news_data: artifacts/data_ingestion/news.tsv
  col_name: ["itemId","category","subcategory","title","abstract","url","title_entities","abstract_entities"]
  item2ind_json: artifacts/data_transformation/ind2uitem.json